name: Keep Streamlit App Alive

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Send Keep-Alive Request
        run: curl -X GET "https://biller.streamlit.app/"
