name: Ping Streamlit App

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Playwright
      run: |
        npm init playwright@latest --yes
        npx playwright install

    - name: Create package.json with type module
      run: |
        echo '{"type": "module"}' > package.json

    - name: Create ping.mjs script
      run: |
        echo "import { chromium } from 'playwright';" > ping.mjs
        echo "(async () => {" >> ping.mjs
        echo "  const browser = await chromium.launch({ headless: true });" >> ping.mjs
        echo "  const page = await browser.newPage();" >> ping.mjs
        echo "  try {" >> ping.mjs
        echo "    const response = await page.goto('https://biller.streamlit.app/');" >> ping.mjs
        echo "    console.log('HTTP Status Code:', response.status());" >> ping.mjs
        echo "    console.log('Final URL:', response.url());" >> ping.mjs
        echo "    console.log('Pinged Streamlit app at:', new Date().toISOString());" >> ping.mjs
        echo "  } catch (error) {" >> ping.mjs
        echo "    console.error('Error pinging Streamlit app:', error);" >> ping.mjs
        echo "  } finally {" >> ping.mjs
        echo "    await browser.close();" >> ping.mjs
        echo "  }" >> ping.mjs
        echo "})();" >> ping.mjs

    - name: Run ping.mjs script
      run: |
        node ping.mjs
