name: Keep Streamlit App Alive
on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Send Request to Streamlit
        run: curl -s -o /dev/null -w "%{http_code}" https://biller.streamlit.app/
