name: Ping Streamlit App

on:
  schedule:
    - cron: '*/2 * * * *'  # Runs every 15 minutes

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
    - name: Ping Streamlit App
      run: |
        curl -s -o /dev/null -w "%{http_code}" https://biller.streamlit.app/
